server:
  port: 0

spring:
  application:
    name: authentication-service

  datasource:
    url: jdbc:mysql://localhost:3306/user_service
    username: root
    password: vampire
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

security:
  jwt:
    secret-key: V9PROAMPRES6FD4S6D5F4S65FD4S65DF4S6D5F4S6D5F4S6D5F4S6D5F4S6D54FS6D4HJGJKLSKJDFLSKDJFLSDKJFLSDFSDF5S4DF65S4D6FS54