server:
  port: 0

spring:
  application:
    name: account-service

  datasource:
    url: jdbc:mysql://localhost:3306/account_service
    username: root
    password: vampire
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update